// Client-side PDF builder for the Business Advisor review, so owners can share
// the strategic review with their team without a server round trip.
import { jsPDF } from "jspdf";
import type { AdvisorAnalysis } from "@/lib/advisor.server";

type BriefLike = {
  business_name?: string;
  industry?: string;
  niche?: string;
  city?: string;
  country?: string;
};

const MARGIN = 48;
const BRAND: [number, number, number] = [16, 94, 62];

export function downloadAdvisorPdf(analysis: AdvisorAnalysis, brief: BriefLike = {}) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxWidth = pageWidth - MARGIN * 2;
  let y = MARGIN;

  function ensureSpace(needed: number) {
    if (y + needed > pageHeight - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  }

  function heading(text: string) {
    ensureSpace(40);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(BRAND[0], BRAND[1], BRAND[2]);
    doc.text(text, MARGIN, y);
    y += 8;
    doc.setDrawColor(220);
    doc.line(MARGIN, y, pageWidth - MARGIN, y);
    y += 16;
    doc.setTextColor(30);
  }

  function body(text: string, opts: { bold?: boolean; size?: number; indent?: number } = {}) {
    const size = opts.size ?? 10.5;
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(size);
    const indent = opts.indent ?? 0;
    const lines = doc.splitTextToSize(text, maxWidth - indent) as string[];
    for (const line of lines) {
      ensureSpace(size + 6);
      doc.text(line, MARGIN + indent, y);
      y += size + 4;
    }
    y += 2;
  }

  function bullets(items: string[]) {
    for (const item of items) body(`•  ${item}`, { indent: 6 });
  }

  // ---- Cover block ----
  doc.setFillColor(BRAND[0], BRAND[1], BRAND[2]);
  doc.rect(0, 0, pageWidth, 90, "F");
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Business Advisor Review", MARGIN, 46);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  const subtitle = [
    brief.business_name || "Your business",
    [brief.industry, brief.niche].filter(Boolean).join(" · "),
    [brief.city, brief.country].filter(Boolean).join(", "),
  ]
    .filter(Boolean)
    .join("  |  ");
  doc.text(subtitle, MARGIN, 66);
  doc.setTextColor(30);
  y = 120;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(
    `Generated by Flash CRM · ${new Date(analysis.generatedAt).toLocaleString()}`,
    MARGIN,
    y,
  );
  doc.setTextColor(30);
  y += 24;

  heading("Verdict");
  body(analysis.verdict, { bold: true });
  if (analysis.positioning) body(analysis.positioning);

  if (analysis.scores.length > 0) {
    heading("Scorecard");
    for (const s of analysis.scores) {
      ensureSpace(34);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10.5);
      doc.text(`${s.label} — ${s.score}/100`, MARGIN, y);
      y += 12;
      doc.setFillColor(235);
      doc.rect(MARGIN, y, maxWidth, 6, "F");
      doc.setFillColor(BRAND[0], BRAND[1], BRAND[2]);
      doc.rect(MARGIN, y, (maxWidth * Math.max(0, Math.min(100, s.score))) / 100, 6, "F");
      y += 14;
      if (s.note) body(s.note, { size: 9.5 });
      y += 2;
    }
  }

  if (analysis.opportunities.length > 0) {
    heading("Growth opportunities");
    for (const o of analysis.opportunities) {
      body(`${o.title}  (${o.impact} impact)`, { bold: true });
      body(o.why, { indent: 6, size: 10 });
      body(`Do: ${o.action}`, { indent: 6, size: 10 });
    }
  }

  if (analysis.local.length > 0) {
    heading("Local market");
    bullets(analysis.local);
  }

  if (analysis.socialPlan.length > 0) {
    heading("Social & traffic plan");
    bullets(analysis.socialPlan.map((s) => `${s.platform}: ${s.recommendation}`));
  }

  if (analysis.pricing.length > 0) {
    heading("Products & pricing");
    bullets(analysis.pricing);
  }

  if (analysis.risks.length > 0) {
    heading("Risks to fix");
    bullets(analysis.risks);
  }

  if (analysis.next7Days.length > 0 || analysis.next90Days.length > 0) {
    heading("Action plan");
    if (analysis.next7Days.length > 0) {
      body("Next 7 days", { bold: true });
      analysis.next7Days.forEach((a, i) => body(`${i + 1}.  ${a}`, { indent: 6 }));
    }
    if (analysis.next90Days.length > 0) {
      body("Next 90 days", { bold: true });
      analysis.next90Days.forEach((a, i) => body(`${i + 1}.  ${a}`, { indent: 6 }));
    }
  }

  if (analysis.kpis.length > 0) {
    heading("KPIs to track");
    bullets(analysis.kpis.map((k) => `${k.name} — target ${k.target}`));
  }

  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(150);
    doc.text(`Flash CRM · Business Advisor · page ${i} of ${pages}`, MARGIN, pageHeight - 24);
  }

  const slug = (brief.business_name || "business").toLowerCase().replace(/[^a-z0-9]+/g, "-");
  doc.save(`flash-advisor-review-${slug}-${new Date().toISOString().slice(0, 10)}.pdf`);
}
