// The WordPress and Shopify plugins are generated by pasting values into source
// code. Text typed in Flas (a site's greeting) must stay text there: for any
// input, the generated file has the same shape as for a harmless one, with
// the typed text only inside the quotes it was put in.
//
// The sources are bundled here rather than in a build script so this file is
// the whole change; the download route runs against a database double.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath, pathToFileURL } from "node:url";
import { beforeEach, describe, it } from "node:test";
import { build } from "esbuild";

import { createDb } from "./support/db-double.mjs";

const root = fileURLToPath(new URL("..", import.meta.url));
const cache = join(root, "node_modules", ".cache");
mkdirSync(cache, { recursive: true });

const stubs = {
  "@tanstack/react-router": "export const createFileRoute = () => (options) => ({ options });",
  "client.server":
    "export const supabaseAdmin = new Proxy({}, { get: (_, key) => globalThis.pluginDownload.db[key] });",
};
const boundaries = {
  name: "plugin-download-boundaries",
  setup(b) {
    b.onResolve({ filter: /.*/ }, (args) => {
      const key = Object.keys(stubs).find((k) => args.path === k || args.path.endsWith("/" + k));
      return key ? { path: key, namespace: "plugin-stub" } : undefined;
    });
    b.onLoad({ filter: /.*/, namespace: "plugin-stub" }, (args) => ({
      contents: stubs[args.path],
      loader: "js",
    }));
  },
};
async function bundle(entry, out) {
  await build({
    entryPoints: [join(root, entry)],
    outfile: join(cache, out),
    format: "esm",
    platform: "node",
    bundle: true,
    logLevel: "error",
    alias: { "@": join(root, "src") },
    plugins: [boundaries],
  });
  return import(pathToFileURL(join(cache, out)).href);
}

const encoding = await bundle("src/lib/plugin-encoding.ts", "flas-plugin-encoding.mjs");
const { buildWordPressPlugin } = await bundle(
  "src/lib/wordpress-plugin.server.ts",
  "flas-plugin-wordpress.mjs",
);
const { buildShopifyPlugin } = await bundle(
  "src/lib/shopify-plugin.server.ts",
  "flas-plugin-shopify.mjs",
);
const { Route: downloadRoute } = await bundle(
  "src/routes/api/public/plugin/download.ts",
  "flas-plugin-download-route.mjs",
);
const { phpSingleQuoted, liquidDoubleQuoted, safeSiteKey, safeOrigin, clampGreeting } = encoding;

const ORIGIN = "https://crm.example.com";
const SITE_KEY = "0123456789abcdef0123456789abcdef";
const ordinary = { origin: ORIGIN, siteKey: SITE_KEY, greeting: "Hi! How can we help?" };

// The stored zip has no compression, so reading it back is walking the
// local file headers.
function unzip(bytes) {
  const buf = Buffer.from(bytes);
  const files = {};
  let at = 0;
  while (buf.readUInt32LE(at) === 0x04034b50) {
    const size = buf.readUInt32LE(at + 18);
    const nameLength = buf.readUInt16LE(at + 26);
    const extraLength = buf.readUInt16LE(at + 28);
    const name = buf.toString("utf8", at + 30, at + 30 + nameLength);
    const start = at + 30 + nameLength + extraLength;
    files[name] = buf.toString("utf8", start, start + size);
    at = start + size;
  }
  return files;
}

const WP_FILE = "flas-crm/flas-crm.php";
const SNIPPET = "flas-crm-shopify/snippets/flas-crm-popup.liquid";
const wordpress = (input) => unzip(buildWordPressPlugin({ ...ordinary, ...input }));
const shopify = (input) => unzip(buildShopifyPlugin({ ...ordinary, ...input }));

/**
 * Reads a PHP single-quoted string the way PHP does. Inside single quotes the
 * only escapes are backslash-backslash and backslash-quote; a backslash before
 * anything else is a literal backslash. Returns the value and the index just
 * past the closing quote.
 */
function readPhpSingleQuoted(source, openingQuote) {
  assert.equal(source[openingQuote], "'", "the string must start at a quote mark");
  let value = "";
  let i = openingQuote + 1;
  while (i < source.length) {
    const ch = source[i];
    if (ch === "\\" && (source[i + 1] === "\\" || source[i + 1] === "'")) {
      value += source[i + 1];
      i += 2;
    } else if (ch === "'") {
      return { value, end: i + 1 };
    } else {
      value += ch;
      i += 1;
    }
  }
  throw new Error("the string never closes");
}

/** Where the greeting's string starts and ends in a generated PHP file. */
function greetingString(file) {
  const marker = "'greeting' => ";
  const at = file.indexOf(marker);
  assert.notEqual(at, -1, "the greeting entry must be in the file");
  const open = at + marker.length;
  return { open, ...readPhpSingleQuoted(file, open) };
}

// What a greeting should read back as: cut to 300 characters, then control
// characters other than newline and tab dropped.
const readsBackAs = (input) =>
  Array.from(input)
    .slice(0, 300)
    .join("")
    .replace(/[\u0000-\u0008\u000B-\u001F\u007F-\u009F]/g, "");

const mixed = Array.from({ length: 5000 }, (_, i) => `\\'"?>$;{}%`[(i * 7 + (i >> 3)) % 10]).join(
  "",
);

const NASTY_GREETINGS = {
  "an escaped quote": "\\'",
  "a lone backslash": "\\",
  "two backslashes then a quote": "a\\\\'b",
  "a planted array entry": "\\', 0 => system($_GET[0]), 1 => 2 //",
  "a quote that closes the call": "'); phpinfo(); //",
  "a trailing backslash": "Welcome to our shop\\",
  "a php close tag and open tag": "?> <?php system('id'); ?> <?=",
  "control characters": "a\u0000b\rc\nd\te\u001bf\u007f",
  "an emoji at the cut": "a".repeat(299) + "\u{1F600}" + "tail",
  "5 KB of mixed quotes and backslashes": mixed,
};

describe("a greeting typed in Flas stays text inside the WordPress plugin", () => {
  const benign = wordpress({ greeting: "Hi" })[WP_FILE];
  const benignString = greetingString(benign);

  for (const [name, greeting] of Object.entries(NASTY_GREETINGS)) {
    it(`reads back exactly as typed: ${name}`, () => {
      const file = wordpress({ greeting })[WP_FILE];
      const { open, value, end } = greetingString(file);

      assert.equal(value, readsBackAs(greeting));
      // The string ends right before the comma that closes the array entry...
      assert.equal(file.slice(end, file.indexOf("\n", end)), ",");
      // ...and nothing of the input is outside it: everything before and after
      // the string is exactly what a harmless greeting produces.
      assert.equal(file.slice(0, open), benign.slice(0, benignString.open));
      assert.equal(file.slice(end), benign.slice(benignString.end));
    });
  }

  it("keeps an ordinary greeting, with an apostrophe or in Arabic, exactly as before", () => {
    for (const greeting of ["It's us", "Hi! How can we help?", "مرحبا! كيف يمكننا مساعدتك؟"]) {
      assert.equal(greetingString(wordpress({ greeting })[WP_FILE]).value, greeting);
    }
    assert.match(wordpress({ greeting: "It's us" })[WP_FILE], /'greeting' => 'It\\'s us',\n/);
  });

  it("cuts a greeting longer than 300 characters to 300", () => {
    const file = wordpress({ greeting: "x".repeat(1000) })[WP_FILE];
    assert.equal(greetingString(file).value, "x".repeat(300));
  });
});

describe("a greeting typed in Flas stays text inside the Shopify snippet", () => {
  const greetingLine = (greeting) =>
    shopify({ greeting })
      [SNIPPET].split("\n")
      .find((line) => line.includes("data-greeting="));
  // The whole line must be this shape; anything the input smuggled in (a quote,
  // a brace, a tag) would break the match.
  const SHAPE =
    /^ {2}data-greeting='\{\{ settings\.flas_popup_greeting \| default: "([^"{}]*)" \| escape \}\}'$/;

  const HOSTILE = {
    "an apostrophe": "How's it going?",
    "a double quote that would close the attribute": '" onmouseover="x',
    "braces that would open Liquid": "}} {% include 'x' %} {{",
    "a closing script tag": "</script>",
    "a line break": "Hello\r\nthere\t!",
    "a tag and an entity": "<img src=x onerror=alert(1)> &amp;",
  };

  for (const [name, greeting] of Object.entries(HOSTILE)) {
    it(`keeps the attribute whole: ${name}`, () => {
      const line = greetingLine(greeting);
      const shape = line.match(SHAPE);
      assert.ok(shape, `the greeting line lost its shape: ${line}`);
      // No double quote, brace or percent-brace pair from the input got through.
      assert.equal((line.match(/"/g) ?? []).length, 2, "only the two quotes of the literal");
      assert.equal((line.match(/\{\{/g) ?? []).length, 1);
      assert.equal((line.match(/\}\}/g) ?? []).length, 1);
      assert.ok(!line.includes("{%") && !line.includes("%}"));
      assert.ok(line.endsWith("| escape }}'"));
      assert.equal(shape[1], liquidDoubleQuoted(greeting));
    });
  }

  it("keeps the words of a greeting that has an apostrophe", () => {
    assert.equal(greetingLine("How's it going?").match(SHAPE)[1], "How's it going?");
  });

  it("cuts a greeting longer than 300 characters to 300", () => {
    assert.equal(greetingLine("y".repeat(900)).match(SHAPE)[1], "y".repeat(300));
  });

  it("prints the shop's own title and greeting settings escaped", () => {
    const snippet = shopify({})[SNIPPET];
    assert.match(
      snippet,
      /data-title="\{\{ settings\.flas_popup_title \| default: 'Chat with us' \| escape \}\}"/,
    );
    assert.match(snippet, /settings\.flas_popup_greeting \| default: "[^"]*" \| escape \}\}'/);
  });
});

describe("the encoders on their own", () => {
  // A tiny deterministic generator, so a failure can be reproduced.
  function strings(count) {
    const alphabet = [
      "\\",
      "'",
      '"',
      "{",
      "}",
      "%",
      "<",
      ">",
      "?",
      "$",
      ";",
      "(",
      ")",
      "\n",
      "\t",
      "\r",
      "\u0000",
      "a",
      "b",
      " ",
      "é",
    ];
    let seed = 12345;
    const next = () => (seed = (seed * 1103515245 + 12345) & 0x7fffffff);
    return Array.from({ length: count }, () =>
      Array.from({ length: next() % 40 }, () => alphabet[next() % alphabet.length]).join(""),
    );
  }

  it("phpSingleQuoted doubles the backslash first, then escapes the quote", () => {
    assert.equal(phpSingleQuoted("\\'"), "\\\\\\'");
    assert.equal(phpSingleQuoted("it's"), "it\\'s");
    assert.equal(phpSingleQuoted("a\\b"), "a\\\\b");
    assert.equal(phpSingleQuoted("a\u0000b\rc\nd\te"), "abc\nd\te");
  });

  it("phpSingleQuoted always reads back as the text it was given", () => {
    for (const text of strings(3000)) {
      const read = readPhpSingleQuoted(`'${phpSingleQuoted(text)}' // rest`, 0);
      assert.equal(read.value, readsBackAs(text));
      assert.equal(
        read.end,
        phpSingleQuoted(text).length + 2,
        `string closed early for ${JSON.stringify(text)}`,
      );
    }
  });

  it("liquidDoubleQuoted leaves nothing that could end the literal or open Liquid", () => {
    for (const text of strings(3000)) {
      const out = liquidDoubleQuoted(text);
      assert.ok(!/["{}\r\n\t\u0000-\u001f\u007f-\u009f]/.test(out), JSON.stringify(out));
    }
    assert.equal(liquidDoubleQuoted('say "hi"'), "say 'hi'");
    assert.equal(liquidDoubleQuoted("a\r\n\tb"), "a b");
    assert.equal(liquidDoubleQuoted("}} {% x %} {{"), " % x % ");
  });

  it("clampGreeting cuts by whole characters", () => {
    assert.equal(clampGreeting("abc"), "abc");
    assert.equal(clampGreeting("a".repeat(301)), "a".repeat(300));
    const cut = clampGreeting("a".repeat(299) + "\u{1F600}\u{1F600}");
    assert.equal(cut, "a".repeat(299) + "\u{1F600}");
  });

  it("safeSiteKey passes real keys and refuses anything else", () => {
    assert.equal(safeSiteKey(SITE_KEY), SITE_KEY);
    assert.equal(safeSiteKey("my-site_KEY-123"), "my-site_KEY-123");
    for (const bad of [
      "",
      "short",
      "abcdefghij'); phpinfo(); //",
      "abcdefghij klmn",
      "abcdefghij<b>",
      "abcdefghij\nklmn",
      SITE_KEY + "\n",
      'abcdefghij"klmn',
      "abcdefghij\\klmn",
      "a".repeat(121),
      null,
      undefined,
      12345678901234,
    ]) {
      assert.throws(() => safeSiteKey(bad), /site key/i, JSON.stringify(bad));
    }
  });

  it("safeOrigin keeps scheme, host and port, and refuses anything else", () => {
    assert.equal(safeOrigin("https://crm.example.com"), "https://crm.example.com");
    assert.equal(safeOrigin("https://CRM.Example.com/some/path?x=1"), "https://crm.example.com");
    assert.equal(safeOrigin("https://crm.example.com:8443"), "https://crm.example.com:8443");
    assert.equal(safeOrigin("http://localhost:3000"), "http://localhost:3000");
    assert.equal(safeOrigin("http://127.0.0.1:8080"), "http://127.0.0.1:8080");
    for (const bad of [
      "",
      "https://crm.example.com'",
      'https://crm.example.com"',
      "https://crm .example.com",
      "https://crm.example.com/<script>",
      "https://crm.example.com\n",
      "https://exa'mple.com",
      "https://crm.example.com\\x",
      "javascript:alert(1)",
      "ftp://crm.example.com",
      "http://crm.example.com",
      "http://localhost.evil.com",
      "http://localhost@evil.com",
      "not a url",
      "https://",
      null,
      undefined,
    ]) {
      assert.throws(() => safeOrigin(bad), /address/i, JSON.stringify(bad));
    }
  });
});

describe("a bad site key or address stops the build", () => {
  const badKeys = [
    "abcdefghij'); phpinfo(); //",
    "abcdefghij klmn",
    "abcdefghij<b>",
    "abcdefghij\nklmn",
  ];
  const badOrigins = [
    "https://crm.example.com'",
    "https://crm .example.com",
    "https://crm.example.com/<x>",
    "https://crm.example.com\n",
    "http://crm.example.com",
  ];

  for (const [platform, build_] of [
    ["WordPress", buildWordPressPlugin],
    ["Shopify", buildShopifyPlugin],
  ]) {
    it(`${platform}: refuses to write a bad site key`, () => {
      for (const siteKey of badKeys)
        assert.throws(() => build_({ ...ordinary, siteKey }), /site key/i);
    });
    it(`${platform}: refuses to write a bad workspace address`, () => {
      for (const origin of badOrigins)
        assert.throws(() => build_({ ...ordinary, origin }), /address/i);
    });
  }

  it("a good key and address appear in the files, once each place they belong", () => {
    const wp = wordpress({})[WP_FILE];
    assert.ok(wp.includes(`define('FLAS_CRM_APP', '${ORIGIN}');`));
    assert.ok(wp.includes(`'site_key' => '${SITE_KEY}',`));
    const snippet = shopify({})[SNIPPET];
    assert.ok(snippet.includes(`src="${ORIGIN}/flas-popup.js"`));
    assert.ok(snippet.includes(`data-site-key="${SITE_KEY}"`));
  });
});

describe("ordinary values give the same files as before the fix, except the changed lines", () => {
  const sha = (text) => createHash("sha256").update(text).digest("hex");

  // Fingerprints of every file the builders produced on origin/main (7aa771d)
  // for ORIGIN, SITE_KEY and a plain greeting.
  const BEFORE = {
    "wp:Hi! How can we help?": {
      [WP_FILE]: "c9f59d0a53135536e0d3771f20779d5480d3fe43176519a384fccfebabfb5c5e",
      "flas-crm/readme.txt": "d95a5d9cc7660bbe7170991f4d3821f85ba49849f15fb745d2037932a46e44a7",
    },
    "wp:How's it going?": {
      [WP_FILE]: "343d9e78b6091d4fc573069e9769ae304e123c329137357e842f545c5cad078a",
      "flas-crm/readme.txt": "d95a5d9cc7660bbe7170991f4d3821f85ba49849f15fb745d2037932a46e44a7",
    },
    "shopify:Hi! How can we help?": {
      [SNIPPET]: "8083e25893243b9520fe15e5da222bb96b9f2c1abcaa72395f025754c9839a44",
      "flas-crm-shopify/sections/flas-lead-capture.liquid":
        "d2955cd8f909fbe5a6e5eeeccb6e04c839ac3acb726c7400c606945817fa9fa7",
      "flas-crm-shopify/INSTALL.txt":
        "94c1aadde0f17ea3a81286bb94f530d77a35a9d30bfed86bc530b96bf335115f",
    },
  };

  for (const greeting of ["Hi! How can we help?", "How's it going?"]) {
    it(`WordPress files are byte for byte the same: ${greeting}`, () => {
      const files = wordpress({ greeting });
      for (const [path, hash] of Object.entries(BEFORE[`wp:${greeting}`])) {
        assert.equal(sha(files[path]), hash, path);
      }
      assert.deepEqual(Object.keys(files).sort(), Object.keys(BEFORE[`wp:${greeting}`]).sort());
    });
  }

  it("Shopify files differ only on the title and greeting lines", () => {
    const files = shopify({});
    const before = BEFORE["shopify:Hi! How can we help?"];
    assert.deepEqual(Object.keys(files).sort(), Object.keys(before).sort());

    // Put the two old lines back and the snippet is what it was.
    const reverted = files[SNIPPET].replace(
      `  data-title="{{ settings.flas_popup_title | default: 'Chat with us' | escape }}"`,
      `  data-title="{{ settings.flas_popup_title | default: 'Chat with us' }}"`,
    ).replace(
      `  data-greeting='{{ settings.flas_popup_greeting | default: "Hi! How can we help?" | escape }}'`,
      `  data-greeting="{{ settings.flas_popup_greeting | default: 'Hi! How can we help?' }}"`,
    );
    assert.notEqual(reverted, files[SNIPPET]);
    assert.equal(sha(reverted), before[SNIPPET]);
    assert.equal(
      sha(files["flas-crm-shopify/sections/flas-lead-capture.liquid"]),
      before["flas-crm-shopify/sections/flas-lead-capture.liquid"],
    );
    assert.equal(
      sha(files["flas-crm-shopify/INSTALL.txt"]),
      before["flas-crm-shopify/INSTALL.txt"],
    );
  });
});

describe("the download route", () => {
  const db = createDb();
  globalThis.pluginDownload = { db: db.client };
  const hostile = "\\', 0 => system($_GET[0]), 1 => 2 //";
  let rows;

  beforeEach(() => {
    rows = { lead_sites: [{ site_key: SITE_KEY, active: true, popup_greeting: hostile }] };
    db.reset(rows);
  });

  const get = (key, platform, base = ORIGIN) => {
    const url = new URL("/api/public/plugin/download", base);
    url.searchParams.set("siteKey", key);
    if (platform) url.searchParams.set("platform", platform);
    return downloadRoute.options.server.handlers.GET({ request: new Request(url) });
  };

  async function quietly(run) {
    const original = console.error;
    const logged = [];
    console.error = (...args) => logged.push(args);
    try {
      return { response: await run(), logged };
    } finally {
      console.error = original;
    }
  }

  it("builds a plugin whose greeting reads back as typed, hostile text included", async () => {
    const response = await get(SITE_KEY);
    assert.equal(response.status, 200);
    assert.equal(response.headers.get("Content-Type"), "application/zip");
    const file = unzip(new Uint8Array(await response.arrayBuffer()))[WP_FILE];
    assert.equal(greetingString(file).value, hostile);
  });

  it("builds the Shopify package from the same record", async () => {
    const response = await get(SITE_KEY, "shopify");
    assert.equal(response.status, 200);
    const files = unzip(new Uint8Array(await response.arrayBuffer()));
    assert.match(
      files[SNIPPET],
      /default: "\\', 0 => system\(\$_GET\[0\]\), 1 => 2 \/\/" \| escape \}\}'/,
    );
  });

  for (const platform of ["wordpress", "shopify"]) {
    it(`answers 500 with the generic text when a stored site key holds code (${platform})`, async () => {
      const key = "abcdefghij'); phpinfo(); //";
      rows.lead_sites.push({ site_key: key, active: true, popup_greeting: "Hi" });
      const { response, logged } = await quietly(() => get(key, platform));
      assert.equal(response.status, 500);
      assert.equal(await response.text(), "Could not build the plugin right now");
      assert.equal(logged.length, 1);
    });
  }

  it("answers 500 with the generic text when the request address cannot be written safely", async () => {
    const { response } = await quietly(() => get(SITE_KEY, "wordpress", "https://exa'mple.com"));
    assert.equal(response.status, 500);
    assert.equal(await response.text(), "Could not build the plugin right now");
  });

  it("still answers 404 for an unknown key and 400 for a missing one", async () => {
    assert.equal((await get("zzzzzzzzzzzzzzzz")).status, 404);
    assert.equal((await get("")).status, 400);
  });
});

// PHP is on GitHub's runners and usually not on a developer's machine. When it
// is here, let PHP itself parse the generated file and say what the greeting is.
const phpProbe = spawnSync("php", ["-v"], { encoding: "utf8" });
const phpMissing = phpProbe.error != null || phpProbe.status !== 0;
if (phpMissing) console.log("# php is not installed here: the real-PHP checks are skipped");

describe("PHP itself agrees", { skip: phpMissing ? "php is not installed here" : false }, () => {
  for (const [name, greeting] of Object.entries(NASTY_GREETINGS)) {
    it(`parses the file and reads the greeting back: ${name}`, () => {
      const dir = mkdtempSync(join(tmpdir(), "flas-plugin-"));
      try {
        const file = join(dir, "flas-crm.php");
        writeFileSync(file, wordpress({ greeting })[WP_FILE]);
        const lint = spawnSync("php", ["-l", file], { encoding: "utf8" });
        assert.equal(lint.status, 0, lint.stdout + lint.stderr);

        const probe = join(dir, "probe.php");
        writeFileSync(
          probe,
          `<?php
define('ABSPATH', '/');
function add_action() {}
function register_activation_hook() {}
function get_option() { return ''; }
require ${JSON.stringify(file)};
$defaults = flas_crm_defaults();
echo bin2hex($defaults['greeting']), ' ', bin2hex($defaults['site_key']);
`,
        );
        const run = spawnSync("php", [probe], { encoding: "utf8" });
        assert.equal(run.status, 0, run.stdout + run.stderr);
        const [greetingHex, keyHex] = run.stdout.split(" ");
        assert.equal(Buffer.from(greetingHex, "hex").toString("utf8"), readsBackAs(greeting));
        assert.equal(Buffer.from(keyHex ?? "", "hex").toString("utf8"), SITE_KEY);
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    });
  }
});
